/* GD32VF103CB */
MEMORY
{
	ROM : ORIGIN = 0x08000000, LENGTH = 128k
	RAM : ORIGIN = 0x20000000, LENGTH = 32k
}

REGION_ALIAS("REGION_TEXT", ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);

REGION_ALIAS("REGION_STACK", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
